# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI_Toast_popup_tutorial_#10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI_Toast_popup_tutorial_#10
pod 'ExytePopupView'

end
